AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  couple-split

  Sample SAM Template for couple-split

Globals:
  Function:
    Timeout: 600
    MemorySize: 256
    LoggingConfig:
      LogFormat: JSON

Resources:
  Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: couple-split-app-project

  CSVConverterLambda:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambda/csv_converter/
      Handler: lambda_function.lambda_handler
      Runtime: python3.11
      Layers:
        - arn:aws:lambda:us-east-1:336392948345:layer:AWSSDKPandas-Python311:1 # Replace with the actual ARN for your region
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref TransactionSplitTable
        - DynamoDBCrudPolicy:
            TableName: !Ref HashTable
        - DynamoDBCrudPolicy:
            TableName: !Ref SplitTable
        - Statement:
            Effect: Allow
            Action:
              - s3:GetObject
              - s3:PutObject
              - s3:DeleteObject
            Resource: arn:aws:s3:::couple-split-app-project/*
      Events:
        MyS3Event:
          Type: S3
          Properties:
            Bucket: !Ref Bucket
            Events: s3:ObjectCreated:*
            Filter:
              S3Key:
                Rules:
                  - Name: prefix
                    Value: input_csv/

  TransactionSplitTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: TransactionSplitTable
      AttributeDefinitions:
        - AttributeName: hash
          AttributeType: S
      KeySchema:
        - AttributeName: hash
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5

  HashTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: HashTable
      AttributeDefinitions:
        - AttributeName: hash
          AttributeType: S
      KeySchema:
        - AttributeName: hash
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 2
        WriteCapacityUnits: 2

  SplitTable:
    Type: AWS::DynamoDB::Table
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain
    Properties:
      TableName: SplitTable
      AttributeDefinitions:
        - AttributeName: userid
          AttributeType: S
        - AttributeName: category
          AttributeType: S
      KeySchema:
        - AttributeName: userid
          KeyType: HASH
        - AttributeName: category
          KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: 2
        WriteCapacityUnits: 2

Outputs:
  CSVConverterLambda:
    Description: CSV Converter Lambda Function ARN
    Value: !GetAtt CSVConverterLambda.Arn
  Bucket:
    Description: S3 Bucket
    Value: !Ref Bucket
  TransactionSplitTable:
    Description: TransactionSplit DynamoDB Table
    Value: !Ref TransactionSplitTable
  HashTable:
    Description: Checksums DynamoDB Table
    Value: !Ref HashTable
  SplitTable:
    Description: SplitTable DynamoDB Table
    Value: !Ref SplitTable
